# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  test:    
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      DBPORT: 5432
      PASSWORD: root
      USER: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ["1.20", "1.19", ">1.20"]
        os: ["ubuntu-latest", "ubuntu-20.04"]
    steps:
    - uses: actions/checkout@v3

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
    # Artifact name
        name: main_file
    # A file, directory or wildcard pattern that describes what to upload
        path: ./main.exe

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}
    
    - name: Build images
      run: docker-compose build

    - name: Run db
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go
      
  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:        
        os: ["ubuntu-latest", "ubuntu-20.04"]
    steps:
    - uses: actions/checkout@v3

    - name: Build App  
      run: go build -v main.go

  docker:
    needs: build
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    
      
